# Attention Metrics and Asset Price Dynamics in Financial Time Series

This project analyzes the relationship between investor attention, proxied by Google Trends data, and financial market behavior. Specifically, it examines whether attention signals and shocks contain predictive information about future returns and volatility across selected assets.

**Author:** Atharva S  
**Date:** April 22 2026

## Imports

In [231]:
import time
import numpy as np
import pandas as pd
import yfinance as yf
from pytrends.request import TrendReq
import matplotlib.pyplot as plt
import statsmodels.api as sm
import os
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

## 2 & 3: Fetching Data and Data Processing

### Price/ETF data

In [37]:
tickers = ['SPY','BTC-USD','TSLA']
asset_data = yf.download(tickers, start = '2021-01-01')
asset_data.columns = ['_'.join(col)for col in asset_data.columns]
asset_data = asset_data.dropna()  # remove weekends

# create features
for ticker in tickers:
    asset_data[ticker+'_log_ret'] = np.log( asset_data['Close_'+ticker] / asset_data['Close_'+ticker].shift(1) )
    asset_data[ticker+'_log_ret_t+1'] = asset_data[ticker+'_log_ret'].shift(-1)
    asset_data[ticker+'_vol_10'] = asset_data[ticker+'_log_ret'].rolling(window=10).std()
    asset_data[ticker+'_vol_10_t+1'] = asset_data[ticker+'_vol_10'].shift(-1)
    asset_data[ticker+'_vol_change_t+1'] = asset_data[ticker+'_vol_10'].diff().shift(-1)
    asset_data[ticker+'_shock_10'] = asset_data[ticker+'_log_ret'] / asset_data[ticker+'_vol_10']
    asset_data[ticker+'_shock_10_t+1'] = asset_data[ticker+'_shock_10'].shift(-1)
    asset_data = asset_data.drop(columns=[i+'_'+ticker for i in ['Open','Close','High','Low','Volume']])  # remove unnecessary columns

asset_data = asset_data.dropna()
asset_data.to_csv('asset_data.csv')  # save to csv for reuse
asset_data

[*********************100%***********************]  3 of 3 completed

,SPY_log_ret,SPY_log_ret_t+1,SPY_vol_10,SPY_vol_10_t+1,SPY_vol_change_t+1,SPY_shock_10,SPY_shock_10_t+1,BTC-USD_log_ret,BTC-USD_log_ret_t+1,BTC-USD_vol_10,...,BTC-USD_vol_change_t+1,BTC-USD_shock_10,BTC-USD_shock_10_t+1,TSLA_log_ret,TSLA_log_ret_t+1,TSLA_vol_10,TSLA_vol_10_t+1,TSLA_vol_change_t+1,TSLA_shock_10,TSLA_shock_10_t+1
Date,,,,,,,,,,,,,,,,,,,,,
2021-01-19,0.007821,0.013743,0.007015,0.007772,0.000757,1.114935,1.768334,-0.020731,-0.014579,0.075489,...,-0.001703,-0.274621,-0.197589,0.022015,0.006962,0.047317,0.047323,0.000006,0.465273,0.147110
2021-01-20,0.013743,0.000912,0.007772,0.007746,-0.000026,1.768334,0.117688,-0.014579,-0.142528,0.073785,...,0.007829,-0.197589,-1.746364,0.006962,-0.006441,0.047323,0.047491,0.000168,0.147110,-0.135624
2021-01-21,0.000912,-0.003546,0.007746,0.006707,-0.001039,0.117688,-0.528676,-0.142528,0.068333,0.081614,...,0.000170,-1.746364,0.835536,-0.006441,0.001951,0.047491,0.041582,-0.005909,-0.135624,0.046914
2021-01-22,-0.003546,0.003936,0.006707,0.006593,-0.000114,-0.528676,0.597026,0.068333,-0.019562,0.081784,...,-0.002157,0.835536,-0.245665,0.001951,0.039555,0.041582,0.035845,-0.005736,0.046914,1.103501
2021-01-25,0.003936,-0.001562,0.006593,0.006116,-0.000477,0.597026,-0.255431,-0.019562,0.006266,0.079627,...,-0.010618,-0.245665,0.090806,0.039555,0.002597,0.035845,0.021645,-0.014200,1.103501,0.119960
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-15,0.007860,0.002454,0.007517,0.007673,0.000156,1.045692,0.319860,0.008370,0.004629,0.018932,...,-0.000342,0.442093,0.248991,0.073431,-0.007812,0.035053,0.034516,-0.000537,2.094864,-0.226335
2026-04-16,0.002454,0.012013,0.007673,0.007520,-0.000153,0.319860,1.597582,0.004629,0.025937,0.018590,...,-0.002189,0.248991,1.581502,-0.007812,0.029691,0.034516,0.028728,-0.005788,-0.226335,1.033524
2026-04-17,0.012013,-0.002002,0.007520,0.008118,0.000598,1.597582,-0.246586,0.025937,-0.016397,0.016400,...,0.001655,1.581502,-0.908166,0.029691,-0.020477,0.028728,0.028567,-0.000161,1.033524,-0.716793
2026-04-20,-0.002002,-0.006568,0.008118,0.009026,0.000908,-0.246586,-0.727741,-0.016397,0.006310,0.018055,...,-0.004539,-0.908166,0.466819,-0.020477,-0.015612,0.028567,0.028350,-0.000217,-0.716793,-0.550673
2026-04-21,-0.006568,0.010076,0.009026,0.006480,-0.002546,-0.727741,1.554881,0.006310,0.025460,0.013516,...,-0.000238,0.466819,1.917488,-0.015612,0.002817,0.028350,0.027594,-0.000756,-0.550673,0.102079

### Attention Data
Note: may take 20-30 minutes

In [2]:
pytrends = TrendReq()
SPY_kws = ['stock market', 'stock market crash','inflation','interest rates','recession','oil prices','crude oil','Fed rate hike','economy']
BTC_kws = ['bitcoin price','crypto crash','crypto','cryptocurrency','buy bitcoin','bitcoin ETF','inflation hedge','risk off','altcoin','memecoin', 'bitcoin mining']
TSLA_kws = ['tesla stock','elon musk','self driving car','electric vehicles','AI stocks','tesla crash','battery technology','lithium price']
kws = SPY_kws + BTC_kws + TSLA_kws

start_date = pd.to_datetime('2021-01-01')
end_date = pd.to_datetime('2026-04-19')
window_months = 6
overlap_months = 2
attention_data = None

current_start = start_date
current_end = current_start

while current_end < end_date:

    current_end = current_start+pd.DateOffset(months=window_months)

    if current_end > end_date:
        current_end = end_date
    
    timeframe = f'{current_start.date()} {current_end.date()}'
    print(f'\nFetching window {timeframe}')
    window_df = pd.DataFrame()


    for kw in kws:
        print(f'\rFetching {kw:<30}',end='',flush=True)

        fetched = False
        attempts = 0

        while (not fetched) and (attempts < 5):
            try:
                attempts += 1
                pytrends.build_payload(
                    kw_list = [kw],
                    timeframe = timeframe
                )
                data = pytrends.interest_over_time()
                fetched = True
            except Exception as e:
                print(f'Attempt {attempts} failed: {e}')
                time.sleep(60)  # wait 60s for rate limit

        data = data.drop(columns=['isPartial'], errors='ignore')  # remove unnecessary column
        window_df[kw] = data[kw]

    # Scale values to match previous window

    if attention_data is None:
        attention_data = window_df.copy()
    else:
        # get overlap index
        overlap = attention_data.index.intersection(window_df.index)

        # calculate scale factors
        scale_factors = {}
        for kw in kws:
            old_vals = attention_data.loc[overlap, kw]
            new_vals = window_df.loc[overlap, kw]

            scale = old_vals.mean() / new_vals.mean()

            scale_factors[kw]=scale

        # scale each kw
        for kw in kws:
            window_df[kw] = window_df[kw] * scale_factors[kw]
    
    # get non-overlapping part
    window_df = window_df.loc[~window_df.index.isin(attention_data.index)]
    attention_data = pd.concat([attention_data,window_df])

    current_start = current_end - pd.DateOffset(months=overlap_months)

attention_data.to_csv('raw_attention_data.csv')
attention_data

Fetching window 2021-01-01 2021-07-01
Fetching stock market                  Attempt 1 failed: The request failed: Google returned a response with code 429
Fetching tesla crash                   Attempt 1 failed: The request failed: Google returned a response with code 429
Fetching lithium price
Fetching window 2021-05-01 2021-11-01
Fetching lithium price
Fetching window 2021-09-01 2022-03-01
Fetching economy                       Attempt 1 failed: The request failed: Google returned a response with code 429
Fetching buy bitcoin                   Attempt 1 failed: The request failed: Google returned a response with code 429
Fetching elon musk                     Attempt 1 failed: The request failed: Google returned a response with code 429
Fetching lithium price
Fetching window 2022-01-01 2022-07-01
Fetching stock market

C:\Users\athar\AppData\Local\Temp\ipykernel_31568\3041995569.py:64: RuntimeWarning: invalid value encountered in scalar divide
  scale = old_vals.mean() / new_vals.mean()

Fetching stock market crash            Attempt 1 failed: The request failed: Google returned a response with code 429
Fetching buy bitcoin                   Attempt 1 failed: The request failed: Google returned a response with code 429
Fetching bitcoin ETF                   Attempt 1 failed: The request failed: Google returned a response with code 429
Fetching tesla stock                   Attempt 1 failed: The request failed: Google returned a response with code 429
Fetching lithium price
Fetching window 2022-05-01 2022-11-01
Fetching lithium price
Fetching window 2022-09-01 2023-03-01
Fetching lithium price
Fetching window 2023-01-01 2023-07-01
Fetching stock market

C:\Users\athar\AppData\Local\Temp\ipykernel_31568\3041995569.py:64: RuntimeWarning: invalid value encountered in scalar divide
  scale = old_vals.mean() / new_vals.mean()

Fetching lithium price
Fetching window 2023-05-01 2023-11-01
Fetching lithium price
Fetching window 2023-09-01 2024-03-01
Fetching lithium price
Fetching window 2024-01-01 2024-07-01
Fetching lithium price
Fetching window 2024-05-01 2024-11-01
Fetching lithium price
Fetching window 2024-09-01 2025-03-01
Fetching bitcoin price                 Attempt 1 failed: The request failed: Google returned a response with code 429
Fetching AI stocks                     Attempt 1 failed: The request failed: Google returned a response with code 429
Fetching lithium price
Fetching window 2025-01-01 2025-07-01
Fetching oil prices                    Attempt 1 failed: The request failed: Google returned a response with code 429
Fetching lithium price
Fetching window 2025-05-01 2025-11-01
Fetching oil prices                    Attempt 1 failed: The request failed: Google returned a response with code 429
Fetching lithium price
Fetching window 2025-09-01 2026-03-01
Fetching lithium price                 Attempt 1 failed: The request failed: Google returned a response with code 429

Fetching window 2026-01-01 2026-04-19
Fetching stock market crash            Attempt 1 failed: The request failed: Google returned a response with code 429
Attempt 2 failed: The request failed: Google returned a response with code 429
Fetching interest rates                Attempt 1 failed: The request failed: Google returned a response with code 429
Fetching lithium price

,stock market,stock market crash,inflation,interest rates,recession,oil prices,crude oil,Fed rate hike,economy,bitcoin price,...,memecoin,bitcoin mining,tesla stock,elon musk,self driving car,electric vehicles,AI stocks,tesla crash,battery technology,lithium price
date,,,,,,,,,,,,,,,,,,,,,
2021-01-01,23.000000,21.000000,24.000000,73.000000,46.000000,43.000000,27.000000,0.0,52.000000,26.000000,...,0.0,19.000000,17.000000,5.000000,57.000000,36.000000,44.000000,0.000000,33.000000,26.000000
2021-01-02,14.000000,17.000000,25.000000,77.000000,53.000000,41.000000,21.000000,0.0,59.000000,39.000000,...,0.0,28.000000,14.000000,6.000000,54.000000,51.000000,42.000000,1.000000,32.000000,30.000000
2021-01-03,13.000000,18.000000,25.000000,70.000000,52.000000,38.000000,26.000000,0.0,57.000000,47.000000,...,0.0,32.000000,13.000000,5.000000,51.000000,45.000000,75.000000,1.000000,47.000000,33.000000
2021-01-04,30.000000,25.000000,29.000000,79.000000,61.000000,69.000000,51.000000,0.0,73.000000,45.000000,...,0.0,25.000000,45.000000,4.000000,70.000000,44.000000,46.000000,2.000000,39.000000,56.000000
2021-01-05,29.000000,26.000000,31.000000,82.000000,68.000000,78.000000,60.000000,0.0,83.000000,37.000000,...,0.0,27.000000,44.000000,4.000000,58.000000,47.000000,50.000000,1.000000,53.000000,66.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-15,27.506775,20.402893,78.490104,127.613327,195.749222,498.996418,433.411618,NaN,149.859575,13.100188,...,NaN,6.149557,16.369440,5.061834,81.550799,124.783128,1209.159045,1.873363,221.773719,234.119008
2026-04-16,29.034929,20.402893,78.490104,124.777475,167.202461,476.314762,371.495673,NaN,172.179086,13.973534,...,NaN,6.764513,16.661751,4.814915,78.832439,183.015254,1577.163972,2.128822,242.565005,273.969052
2026-04-17,38.203854,22.103134,82.850666,124.777475,167.202461,884.584558,603.680468,NaN,178.556089,15.720226,...,NaN,8.609380,19.584865,7.160643,84.269159,128.942566,2260.601693,5.109172,270.286720,268.987796
2026-04-18,17.573773,16.152291,61.047859,104.926513,122.343264,498.996418,386.974659,NaN,130.728565,12.226842,...,NaN,5.534602,5.846228,5.061834,81.550799,99.826502,893.726251,2.469433,200.982433,204.231475
2026-04-19,18.337850,31.454461,61.047859,107.762365,134.577590,340.224830,263.142768,NaN,130.728565,11.353497,...,NaN,6.764513,4.384671,4.814915,82.909979,95.667065,736.009854,1.532752,166.330289,189.287708

In [16]:
### Create attention data features
attention_data = pd.read_csv('raw_attention_data.csv', index_col='date')
attention_data = attention_data.drop(columns=['Fed rate hike','memecoin'])  # remove columns with too many missing values

for kw in kws:
  if kw == 'Fed rate hike' or kw == 'memecoin':
    continue
  attention_data[kw + '_diff'] = attention_data[kw].diff()
  attention_data[kw+'_shock_10'] = (attention_data[kw]-attention_data[kw].rolling(window=10).mean()) / attention_data[kw].rolling(window=10).std()

attention_data = attention_data.dropna()
attention_data.to_csv('attention_data.csv')
attention_data

,stock market,stock market crash,inflation,interest rates,recession,oil prices,crude oil,economy,bitcoin price,crypto crash,...,electric vehicles_diff,electric vehicles_shock_10,AI stocks_diff,AI stocks_shock_10,tesla crash_diff,tesla crash_shock_10,battery technology_diff,battery technology_shock_10,lithium price_diff,lithium price_shock_10
date,,,,,,,,,,,,,,,,,,,,,
2021-01-10,15.000000,29.000000,26.000000,70.000000,56.000000,42.000000,29.000000,66.000000,44.000000,1.000000,...,2.000000,0.357938,15.000000,1.751993,-1.000000,0.241747,-6.000000,0.159384,-1.000000,0.378763
2021-01-11,32.000000,32.000000,31.000000,81.000000,70.000000,71.000000,55.000000,85.000000,70.000000,4.000000,...,6.000000,1.571240,-9.000000,0.855122,0.000000,0.106735,17.000000,1.645489,7.000000,0.614288
2021-01-12,31.000000,33.000000,33.000000,78.000000,68.000000,69.000000,59.000000,87.000000,55.000000,1.000000,...,3.000000,1.750014,1.000000,0.768610,-1.000000,-0.502244,2.000000,1.595723,18.000000,1.543675
2021-01-13,30.000000,29.000000,34.000000,78.000000,76.000000,72.000000,60.000000,84.000000,45.000000,1.000000,...,5.000000,1.922684,-28.000000,-1.311322,0.000000,-0.588348,-13.000000,0.035190,0.000000,1.577657
2021-01-14,30.000000,32.000000,35.000000,74.000000,68.000000,70.000000,58.000000,87.000000,43.000000,1.000000,...,-3.000000,1.170791,-1.000000,-1.285372,0.000000,-0.588348,0.000000,-0.156102,10.000000,1.851923
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-15,27.506775,20.402893,78.490104,127.613327,195.749222,498.996418,433.411618,149.859575,13.100188,0.906402,...,16.637750,-0.224818,105.144265,-0.239597,0.340611,-0.653552,6.930429,-0.363903,4.981255,-0.080602
2026-04-16,29.034929,20.402893,78.490104,124.777475,167.202461,476.314762,371.495673,172.179086,13.973534,1.087682,...,58.232126,1.189642,368.004927,0.553388,0.255459,-0.430880,20.791286,-0.057341,39.850044,0.557387
2026-04-17,38.203854,22.103134,82.850666,124.777475,167.202461,884.584558,603.680468,178.556089,15.720226,1.812803,...,-54.072689,0.306897,683.437721,2.384378,2.980351,2.340255,27.721715,1.886701,-4.981255,1.436876
2026-04-18,17.573773,16.152291,61.047859,104.926513,122.343264,498.996418,386.974659,130.728565,12.226842,1.268962,...,-29.116063,-0.856770,-1366.875443,-0.666577,-2.639739,-0.197844,-69.304287,-0.386519,-64.756321,-0.243737
2026-04-19,18.337850,31.454461,61.047859,107.762365,134.577590,340.224830,263.142768,130.728565,11.353497,1.087682,...,-4.159438,-0.894935,-157.716397,-0.890724,-0.936682,-0.986438,-34.652144,-1.218807,-14.943766,-0.628584

### Allign Data

In [30]:
asset_data = pd.read_csv('asset_data.csv')
attention_data = pd.read_csv('attention_data.csv')
data = pd.concat([asset_data,attention_data],axis=1)
data = data.dropna()
data.to_csv('data.csv')
data

,Date,SPY_log_ret,SPY_log_ret_t+1,SPY_vol_10,SPY_vol_10_t+1,SPY_vol_change,SPY_shock_10,SPY_shock_10_t+1,BTC-USD_log_ret,BTC-USD_log_ret_t+1,...,electric vehicles_diff,electric vehicles_shock_10,AI stocks_diff,AI stocks_shock_10,tesla crash_diff,tesla crash_shock_10,battery technology_diff,battery technology_shock_10,lithium price_diff,lithium price_shock_10
0,2021-01-20,0.013744,0.000911,0.007772,0.007746,0.000757,1.768383,0.117644,-0.014579,-0.142528,...,2.000000,0.357938,15.000000,1.751993,-1.000000,0.241747,-6.000000,0.159384,-1.000000,0.378763
1,2021-01-21,0.000911,-0.003546,0.007746,0.006707,-0.000026,0.117644,-0.528734,-0.142528,0.068333,...,6.000000,1.571240,-9.000000,0.855122,0.000000,0.106735,17.000000,1.645489,7.000000,0.614288
2,2021-01-22,-0.003546,0.003936,0.006707,0.006593,-0.001039,-0.528734,0.597069,0.068333,-0.019562,...,3.000000,1.750014,1.000000,0.768610,-1.000000,-0.502244,2.000000,1.595723,18.000000,1.543675
3,2021-01-25,0.003936,-0.001562,0.006593,0.006116,-0.000114,0.597069,-0.255441,-0.019562,0.006266,...,5.000000,1.922684,-28.000000,-1.311322,0.000000,-0.588348,-13.000000,0.035190,0.000000,1.577657
4,2021-01-26,-0.001562,-0.024744,0.006116,0.010292,-0.000477,-0.255441,-2.404135,0.006266,-0.067874,...,-3.000000,1.170791,-1.000000,-1.285372,0.000000,-0.588348,0.000000,-0.156102,10.000000,1.851923
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1314,2026-04-15,0.007860,0.002454,0.007517,0.007673,-0.002588,1.045692,0.319860,0.008370,0.004629,...,-12.811396,-1.396643,-49.403305,-1.951673,-1.862237,-2.458357,-18.904243,-1.947492,-13.347635,-1.585751
1315,2026-04-16,0.002454,0.012013,0.007673,0.007520,0.000156,0.319860,1.597582,0.004629,0.025937,...,-4.270465,-1.690605,148.209916,-0.477153,1.513068,-0.164632,-6.301414,-1.813714,6.673817,-0.735389
1316,2026-04-17,0.012013,-0.002002,0.007520,0.008118,-0.000153,1.597582,-0.246586,0.025937,-0.016397,...,23.487559,1.693843,0.000000,-0.346071,-0.232780,-0.429573,12.602829,-0.727047,13.347635,0.805788
1317,2026-04-20,-0.002002,-0.006568,0.008118,0.009026,0.000598,-0.246586,-0.727741,-0.016397,0.006310,...,-12.811396,-0.273196,-49.403305,-0.742275,0.814729,0.672610,6.301414,-0.271808,0.000000,0.649671
1318,2026-04-21,-0.006568,0.010076,0.009026,0.006480,0.000908,-0.727741,1.554881,0.006310,0.025183,...,4.270465,0.336766,148.209916,0.725351,-0.465559,0.081570,6.301414,0.209981,6.673817,1.179396

## 4: Exploratory Data Analysis

In [24]:
data = pd.read_csv('data.csv')
kws_map = {
    'SPY_kws': SPY_kws,
    'BTC-USD_kws': BTC_kws,
    'TSLA_kws': TSLA_kws
}



# generate a 'plots' folder to store plot files
os.makedirs('plots',exist_ok=True)


# loop over tickers, keywords, and stats to create plots
for ticker in tickers:
    for kw in kws_map[ticker+'_kws']:
        if kw == 'Fed rate hike' or kw == 'memecoin':  # skip problematic columns
            continue

        fig,axes = plt.subplots(3,3,figsize=(12,10),sharex=True) # generate 3x3 subplot of for each ticker kw pair
        axes=axes.flatten()
        i=0

        for ticker_stat in ['_log_ret','_vol_10','_shock_10']:
            for kw_stat in ['','_diff','_shock_10']:
                ax = axes[i]

                x = (data[ticker+ticker_stat][::10] - data[ticker+ticker_stat][::10].min()) / (
                    data[ticker+ticker_stat][::10].max() - data[ticker+ticker_stat][::10].min()
                )

                y = (data[kw+kw_stat][::10] - data[kw+kw_stat][::10].min()) / (
                    data[kw+kw_stat][::10].max() - data[kw+kw_stat][::10].min()
                )

                ax.plot(data.index[::10], x, label=ticker+ticker_stat)
                ax.plot(data.index[::10], y, label=kw+kw_stat)

                # correlation coefficient
                corr = x.corr(y)

                # put in top-left corner
                ax.text(
                    0.02, 0.98,
                    f"corr={corr:.2f}",
                    transform=ax.transAxes,
                    ha='left',
                    va='top',
                    fontsize=9
                )

                ax.set_title(f'{ticker+ticker_stat} vs {kw+kw_stat}')
                ax.legend(fontsize=8)

                i += 1
        
        plt.tight_layout()
        path = 'plots/' + ticker + '_'+kw+'.png'
        plt.savefig(path,dpi=300)
        plt.close()

## 5: Modeling

#### Train-Test Split and Processing

In [31]:
train = data.loc[:'2025-12-31']
test = data.loc[:'2026-01-02']

#### Baseline Volatility Model (AR)

SPY (overall market)

In [232]:
y_train = train['SPY_shock_10_t+1']
y_test = test['SPY_shock_10_t+1']
X_train = pd.DataFrame()
X_test = pd.DataFrame()
X_train['lag0'] = train['SPY_shock_10']
X_test['lag0'] = test['SPY_shock_10']
X_train['lag1']=X_train['lag0'].shift(1)
X_test['lag1']=X_test['lag0'].shift(1)
X_train['lag2']=X_train['lag0'].shift(2)
X_test['lag2']=X_test['lag0'].shift(2)
X_train = X_train.dropna()
X_test = X_test.dropna()
y_train = y_train[X_train.index]
y_test = y_test[X_test.index]
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)

model = sm.OLS(y,X).fit()
print(model.summary())

predictions = model.predict(X_test)
SPY_base_mse = mean_squared_error(y_test, predictions)
SPY_base_mae = mean_absolute_error(y_test, predictions)
print(f'MSE: {SPY_base_mse}')
print(f'MAE: {SPY_base_mae}')

                             OLS Regression Results
================================================================================
Dep. Variable:     BTC-USD_shock_10_t+1   R-squared:                       0.003
Model:                              OLS   Adj. R-squared:                  0.001
Method:                   Least Squares   F-statistic:                     1.401
Date:                  Wed, 22 Apr 2026   Prob (F-statistic):              0.241
Time:                          22:39:58   Log-Likelihood:                -1871.8
No. Observations:                  1317   AIC:                             3752.
Df Residuals:                      1313   BIC:                             3772.
Df Model:                             3
Covariance Type:              nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0245      0.028      0.884      0.377      -0.030       0.079
BTC-USD_shock_10     0.0304      0.028      1.100      0.272      -0.024       0.085
lag1                 0.0171      0.028      0.620      0.536      -0.037       0.071
lag2                 0.0430      0.028      1.560      0.119      -0.011       0.097
==============================================================================
Omnibus:                        1.740   Durbin-Watson:                   1.996
Prob(Omnibus):                  0.419   Jarque-Bera (JB):                1.672
Skew:                           0.040   Prob(JB):                        0.434
Kurtosis:                       3.155   Cond. No.                         1.06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.0618487810164507
MAE: 0.8108720037301871

BTC-USD

In [234]:
y_train = train['BTC-USD_shock_10_t+1']
y_test = test['BTC-USD_shock_10_t+1']
X_train = pd.DataFrame()
X_test = pd.DataFrame()
X_train['lag0'] = train['BTC-USD_shock_10']
X_test['lag0'] = test['BTC-USD_shock_10']
X_train['lag1']=X_train['lag0'].shift(1)
X_test['lag1']=X_test['lag0'].shift(1)
X_train['lag2']=X_train['lag0'].shift(2)
X_test['lag2']=X_test['lag0'].shift(2)
X_train = X_train.dropna()
X_test = X_test.dropna()
y_train = y_train[X_train.index]
y_test = y_test[X_test.index]
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)

model = sm.OLS(y,X).fit()
print(model.summary())

predictions = model.predict(X_test)
BTC_base_mse = mean_squared_error(y_test, predictions)
BTC_base_mae = mean_absolute_error(y_test, predictions)
print(f'MSE: {BTC_base_mse}')
print(f'MAE: {BTC_base_mae}')

                             OLS Regression Results
================================================================================
Dep. Variable:     BTC-USD_shock_10_t+1   R-squared:                       0.003
Model:                              OLS   Adj. R-squared:                  0.001
Method:                   Least Squares   F-statistic:                     1.401
Date:                  Wed, 22 Apr 2026   Prob (F-statistic):              0.241
Time:                          22:43:30   Log-Likelihood:                -1871.8
No. Observations:                  1317   AIC:                             3752.
Df Residuals:                      1313   BIC:                             3772.
Df Model:                             3
Covariance Type:              nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0245      0.028      0.884      0.377      -0.030       0.079
BTC-USD_shock_10     0.0304      0.028      1.100      0.272      -0.024       0.085
lag1                 0.0171      0.028      0.620      0.536      -0.037       0.071
lag2                 0.0430      0.028      1.560      0.119      -0.011       0.097
==============================================================================
Omnibus:                        1.740   Durbin-Watson:                   1.996
Prob(Omnibus):                  0.419   Jarque-Bera (JB):                1.672
Skew:                           0.040   Prob(JB):                        0.434
Kurtosis:                       3.155   Cond. No.                         1.06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 0.9572324859720662
MAE: 0.7865862780782585

TSLA

In [236]:
y_train = train['TSLA_shock_10_t+1']
y_test = test['TSLA_shock_10_t+1']
X_train = pd.DataFrame()
X_test = pd.DataFrame()
X_train['lag0'] = train['TSLA_shock_10']
X_test['lag0'] = test['TSLA_shock_10']
X_train['lag1']=X_train['lag0'].shift(1)
X_test['lag1']=X_test['lag0'].shift(1)
X_train['lag2']=X_train['lag0'].shift(2)
X_test['lag2']=X_test['lag0'].shift(2)
X_train = X_train.dropna()
X_test = X_test.dropna()
y_train = y_train[X_train.index]
y_test = y_test[X_test.index]
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)

model = sm.OLS(y,X).fit()
print(model.summary())

predictions = model.predict(X_test)
TSLA_base_mse = mean_squared_error(y_test, predictions)
TSLA_base_mae = mean_absolute_error(y_test, predictions)
print(f'MSE: {TSLA_base_mse}')
print(f'MAE: {TSLA_base_mae}')

                             OLS Regression Results
================================================================================
Dep. Variable:     BTC-USD_shock_10_t+1   R-squared:                       0.003
Model:                              OLS   Adj. R-squared:                  0.001
Method:                   Least Squares   F-statistic:                     1.401
Date:                  Wed, 22 Apr 2026   Prob (F-statistic):              0.241
Time:                          22:45:21   Log-Likelihood:                -1871.8
No. Observations:                  1317   AIC:                             3752.
Df Residuals:                      1313   BIC:                             3772.
Df Model:                             3
Covariance Type:              nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0245      0.028      0.884      0.377      -0.030       0.079
BTC-USD_shock_10     0.0304      0.028      1.100      0.272      -0.024       0.085
lag1                 0.0171      0.028      0.620      0.536      -0.037       0.071
lag2                 0.0430      0.028      1.560      0.119      -0.011       0.097
==============================================================================
Omnibus:                        1.740   Durbin-Watson:                   1.996
Prob(Omnibus):                  0.419   Jarque-Bera (JB):                1.672
Skew:                           0.040   Prob(JB):                        0.434
Kurtosis:                       3.155   Cond. No.                         1.06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.0753266587526351
MAE: 0.8136118517113207

#### Augmented Volatility Model (with attention metrics)

SPY (overall market)

In [ ]:
# analyze performance for each metric and find best improvements
SPY_best_metrics = []
y_train = train['SPY_shock_10_t+1']
y_test = test['SPY_shock_10_t+1']
for kw in [i for i in SPY_kws if i!='Fed rate hike']:
    for stat in ['','_diff','_shock_10']:

        y_train = pd.DataFrame()
        y_test = pd.DataFrame()
        y_train = train['SPY_shock_10_t+1']
        y_test = test['SPY_shock_10_t+1']
        X_train = pd.DataFrame()
        X_test = pd.DataFrame()
        X_train[kw+stat]=train[kw+stat]
        X_test[kw+stat]=test[kw+stat]
        X_train['lag0'] = train['SPY_shock_10']
        X_test['lag0'] = test['SPY_shock_10']
        X_train['lag1']=X_train['lag0'].shift(1)
        X_test['lag1']=X_test['lag0'].shift(1)
        X_train['lag2']=X_train['lag0'].shift(2)
        X_test['lag2']=X_test['lag0'].shift(2)
        X_train = X_train.dropna()
        X_test = X_test.dropna()
        y_train = y_train[X_train.index]
        y_test = y_test[X_test.index]
        X_train = sm.add_constant(X_train)
        X_test = sm.add_constant(X_test)

        model = sm.OLS(y_train,X_train).fit()
        predictions = model.predict(X_test)
        mse = mean_squared_error(y_test, predictions)
        if mse<SPY_base_mse:  # only analyze kw+stat pairs with improvement over baseline
            print(model.summary())
            print(f'MSE: {mse}')
            SPY_best_metrics.append((kw+stat,mse))

                            OLS Regression Results
==============================================================================
Dep. Variable:       SPY_shock_10_t+1   R-squared:                       0.012
Model:                            OLS   Adj. R-squared:                 -0.008
Method:                 Least Squares   F-statistic:                    0.6055
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.659
Time:                        22:41:40   Log-Likelihood:                -287.64
No. Observations:                 201   AIC:                             585.3
Df Residuals:                     196   BIC:                             601.8
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.1457      0.164      0.888      0.376      -0.178       0.469
stock market     0.0006      0.006      0.101      0.920      -0.011       0.013
lag0            -0.0379      0.071     -0.532      0.595      -0.178       0.102
lag1            -0.0520      0.071     -0.731      0.465      -0.192       0.088
lag2            -0.0938      0.071     -1.322      0.188      -0.234       0.046
==============================================================================
Omnibus:                       10.386   Durbin-Watson:                   1.993
Prob(Omnibus):                  0.006   Jarque-Bera (JB):               10.749
Skew:                          -0.563   Prob(JB):                      0.00463
Kurtosis:                       3.121   Cond. No.                         61.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.024476454341331
MAE: 0.7959707533163274
                            OLS Regression Results
==============================================================================
Dep. Variable:       SPY_shock_10_t+1   R-squared:                       0.012
Model:                            OLS   Adj. R-squared:                 -0.008
Method:                 Least Squares   F-statistic:                    0.6039
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.660
Time:                        22:41:40   Log-Likelihood:                -287.64
No. Observations:                 201   AIC:                             585.3
Df Residuals:                     196   BIC:                             601.8
Df Model:                           4
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.1605      0.074      2.162      0.032       0.014       0.307
stock market_diff    -0.0004      0.007     -0.062      0.950      -0.014       0.014
lag0                 -0.0386      0.071     -0.542      0.589      -0.179       0.102
lag1                 -0.0522      0.071     -0.733      0.464      -0.192       0.088
lag2                 -0.0933      0.071     -1.313      0.191      -0.233       0.047
==============================================================================
Omnibus:                       10.435   Durbin-Watson:                   1.992
Prob(Omnibus):                  0.005   Jarque-Bera (JB):               10.808
Skew:                          -0.565   Prob(JB):                      0.00450
Kurtosis:                       3.121   Cond. No.                         11.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.0245095238568442
MAE: 0.7959685842625182
                            OLS Regression Results
==============================================================================
Dep. Variable:       SPY_shock_10_t+1   R-squared:                       0.014
Model:                            OLS   Adj. R-squared:                 -0.007
Method:                 Least Squares   F-statistic:                    0.6764
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.609
Time:                        22:41:40   Log-Likelihood:                -287.49
No. Observations:                 201   AIC:                             585.0
Df Residuals:                     196   BIC:                             601.5
Df Model:                           4
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                     0.1602      0.074      2.160      0.032       0.014       0.306
stock market_shock_10     0.0433      0.080      0.539      0.591      -0.115       0.202
lag0                     -0.0362      0.071     -0.509      0.611      -0.176       0.104
lag1                     -0.0513      0.071     -0.722      0.471      -0.192       0.089
lag2                     -0.0949      0.071     -1.339      0.182      -0.235       0.045
==============================================================================
Omnibus:                       10.092   Durbin-Watson:                   1.999
Prob(Omnibus):                  0.006   Jarque-Bera (JB):               10.394
Skew:                          -0.554   Prob(JB):                      0.00553
Kurtosis:                       3.125   Cond. No.                         1.27
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.0230143081816274
MAE: 0.7942659992935432
                            OLS Regression Results
==============================================================================
Dep. Variable:       SPY_shock_10_t+1   R-squared:                       0.013
Model:                            OLS   Adj. R-squared:                 -0.007
Method:                 Least Squares   F-statistic:                    0.6528
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.626
Time:                        22:41:40   Log-Likelihood:                -287.54
No. Observations:                 201   AIC:                             585.1
Df Residuals:                     196   BIC:                             601.6
Df Model:                           4
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                  0.2221      0.157      1.413      0.159      -0.088       0.532
stock market crash    -0.0024      0.005     -0.444      0.657      -0.013       0.008
lag0                  -0.0399      0.071     -0.562      0.575      -0.180       0.100
lag1                  -0.0516      0.071     -0.726      0.469      -0.192       0.089
lag2                  -0.0916      0.071     -1.291      0.198      -0.232       0.048
==============================================================================
Omnibus:                       10.745   Durbin-Watson:                   1.991
Prob(Omnibus):                  0.005   Jarque-Bera (JB):               11.149
Skew:                          -0.573   Prob(JB):                      0.00379
Kurtosis:                       3.137   Cond. No.                         63.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.0234988372712481
MAE: 0.7944647415650804
                            OLS Regression Results
==============================================================================
Dep. Variable:       SPY_shock_10_t+1   R-squared:                       0.016
Model:                            OLS   Adj. R-squared:                 -0.004
Method:                 Least Squares   F-statistic:                    0.7816
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.538
Time:                        22:41:40   Log-Likelihood:                -287.28
No. Observations:                 201   AIC:                             584.6
Df Residuals:                     196   BIC:                             601.1
Df Model:                           4
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       0.1591      0.074      2.147      0.033       0.013       0.305
stock market crash_diff    -0.0062      0.007     -0.840      0.402      -0.021       0.008
lag0                       -0.0394      0.071     -0.555      0.579      -0.179       0.101
lag1                       -0.0461      0.071     -0.645      0.519      -0.187       0.095
lag2                       -0.0906      0.071     -1.278      0.203      -0.230       0.049
==============================================================================
Omnibus:                       10.591   Durbin-Watson:                   1.981
Prob(Omnibus):                  0.005   Jarque-Bera (JB):               11.032
Skew:                          -0.572   Prob(JB):                      0.00402
Kurtosis:                       3.099   Cond. No.                         11.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.0208514711815135
MAE: 0.7968882283016289
                            OLS Regression Results
==============================================================================
Dep. Variable:       SPY_shock_10_t+1   R-squared:                       0.012
Model:                            OLS   Adj. R-squared:                 -0.008
Method:                 Least Squares   F-statistic:                    0.6065
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.658
Time:                        22:41:40   Log-Likelihood:                -287.63
No. Observations:                 201   AIC:                             585.3
Df Residuals:                     196   BIC:                             601.8
Df Model:                           4
Covariance Type:            nonrobust
===============================================================================================
                                  coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
const                           0.1609      0.074      2.166      0.032       0.014       0.307
stock market crash_shock_10     0.0087      0.072      0.120      0.904      -0.133       0.151
lag0                           -0.0380      0.071     -0.534      0.594      -0.178       0.102
lag1                           -0.0534      0.072     -0.745      0.457      -0.195       0.088
lag2                           -0.0946      0.071     -1.325      0.187      -0.235       0.046
==============================================================================
Omnibus:                       10.246   Durbin-Watson:                   1.994
Prob(Omnibus):                  0.006   Jarque-Bera (JB):               10.592
Skew:                          -0.559   Prob(JB):                      0.00501
Kurtosis:                       3.117   Cond. No.                         1.31
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.0244542184057033
MAE: 0.7958936190729947
                            OLS Regression Results
==============================================================================
Dep. Variable:       SPY_shock_10_t+1   R-squared:                       0.016
Model:                            OLS   Adj. R-squared:                 -0.004
Method:                 Least Squares   F-statistic:                    0.8213
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.513
Time:                        22:41:40   Log-Likelihood:                -287.20
No. Observations:                 201   AIC:                             584.4
Df Residuals:                     196   BIC:                             600.9
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.1385      0.330     -0.419      0.675      -0.790       0.513
inflation      0.0082      0.009      0.929      0.354      -0.009       0.026
lag0          -0.0422      0.071     -0.594      0.553      -0.182       0.098
lag1          -0.0589      0.071     -0.826      0.410      -0.200       0.082
lag2          -0.0919      0.071     -1.298      0.196      -0.231       0.048
==============================================================================
Omnibus:                        9.969   Durbin-Watson:                   1.996
Prob(Omnibus):                  0.007   Jarque-Bera (JB):               10.294
Skew:                          -0.552   Prob(JB):                      0.00582
Kurtosis:                       3.100   Cond. No.                         172.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.0200374311904816
MAE: 0.7930545386063236
                            OLS Regression Results
==============================================================================
Dep. Variable:       SPY_shock_10_t+1   R-squared:                       0.012
Model:                            OLS   Adj. R-squared:                 -0.008
Method:                 Least Squares   F-statistic:                    0.6041
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.660
Time:                        22:41:40   Log-Likelihood:                -287.64
No. Observations:                 201   AIC:                             585.3
Df Residuals:                     196   BIC:                             601.8
Df Model:                           4
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const              0.1606      0.074      2.164      0.032       0.014       0.307
inflation_diff    -0.0008      0.011     -0.069      0.945      -0.022       0.021
lag0              -0.0384      0.071     -0.540      0.590      -0.179       0.102
lag1              -0.0521      0.071     -0.732      0.465      -0.192       0.088
lag2              -0.0944      0.072     -1.314      0.190      -0.236       0.047
==============================================================================
Omnibus:                       10.414   Durbin-Watson:                   1.993
Prob(Omnibus):                  0.005   Jarque-Bera (JB):               10.781
Skew:                          -0.564   Prob(JB):                      0.00456
Kurtosis:                       3.122   Cond. No.                         7.60
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.0245048187457901
MAE: 0.7957359027680404
                            OLS Regression Results
==============================================================================
Dep. Variable:       SPY_shock_10_t+1   R-squared:                       0.015
Model:                            OLS   Adj. R-squared:                 -0.005
Method:                 Least Squares   F-statistic:                    0.7339
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.570
Time:                        22:41:40   Log-Likelihood:                -287.38
No. Observations:                 201   AIC:                             584.8
Df Residuals:                     196   BIC:                             601.3
Df Model:                           4
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                  0.1599      0.074      2.158      0.032       0.014       0.306
inflation_shock_10     0.0545      0.076      0.720      0.473      -0.095       0.204
lag0                  -0.0369      0.071     -0.520      0.604      -0.177       0.103
lag1                  -0.0507      0.071     -0.714      0.476      -0.191       0.089
lag2                  -0.0915      0.071     -1.290      0.198      -0.231       0.048
==============================================================================
Omnibus:                       10.227   Durbin-Watson:                   2.000
Prob(Omnibus):                  0.006   Jarque-Bera (JB):               10.537
Skew:                          -0.557   Prob(JB):                      0.00515
Kurtosis:                       3.135   Cond. No.                         1.27
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.0218298167999134
MAE: 0.7948324535058616
                            OLS Regression Results
==============================================================================
Dep. Variable:       SPY_shock_10_t+1   R-squared:                       0.014
Model:                            OLS   Adj. R-squared:                 -0.006
Method:                 Least Squares   F-statistic:                    0.7164
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.582
Time:                        22:41:40   Log-Likelihood:                -287.41
No. Observations:                 201   AIC:                             584.8
Df Residuals:                     196   BIC:                             601.3
Df Model:                           4
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const             -0.1844      0.520     -0.354      0.723      -1.210       0.842
interest rates     0.0048      0.007      0.670      0.504      -0.009       0.019
lag0              -0.0342      0.071     -0.480      0.632      -0.175       0.106

In [249]:
# create model with 5 best metrics
SPY_t5 = sorted(SPY_best_metrics, key=lambda x: x[1])[:5]
for metric in SPY_t5:
    print(f'Metric: {metric[0]}   MSE: {metric[1]}')
SPY_t5 = [x[0] for x in SPY_t5]
y_train = train['SPY_shock_10_t+1']
y_test = test['SPY_shock_10_t+1']
X_train = pd.DataFrame()
X_test = pd.DataFrame()
X_train[SPY_t5]=train[SPY_t5]
X_test[SPY_t5]=test[SPY_t5]
X_train['lag0'] = train['SPY_shock_10']
X_test['lag0'] = test['SPY_shock_10']
X_train['lag1']=X_train['lag0'].shift(1)
X_test['lag1']=X_test['lag0'].shift(1)
X_train['lag2']=X_train['lag0'].shift(2)
X_test['lag2']=X_test['lag0'].shift(2)
X_train = X_train.dropna()
X_test = X_test.dropna()
y_train = y_train[X_train.index]
y_test = y_test[X_test.index]
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)

model = sm.OLS(y_train,X_train).fit()
predictions = model.predict(X_test)
mse = mean_squared_error(y_test, predictions)
print(model.summary())
print(f'MSE: {mse}')
print(f'MAE: {mean_absolute_error(y_test,predictions)}')

Metric: crude oil_diff   MSE: 1.0165508007783297
Metric: interest rates_shock_10   MSE: 1.0177028024535557
Metric: oil prices_shock_10   MSE: 1.0182724835273718
Metric: inflation   MSE: 1.0200374311904816
Metric: economy_shock_10   MSE: 1.0206951826472919
                            OLS Regression Results
==============================================================================
Dep. Variable:       SPY_shock_10_t+1   R-squared:                       0.048
Model:                            OLS   Adj. R-squared:                  0.009
Method:                 Least Squares   F-statistic:                     1.221
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.289
Time:                        23:15:21   Log-Likelihood:                -283.88
No. Observations:                 201   AIC:                             585.8
Df Residuals:                     192   BIC:                             615.5
Df Model:                           8
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       0.0540      0.366      0.148      0.883      -0.668       0.776
crude oil_diff             -0.0157      0.007     -2.361      0.019      -0.029      -0.003
interest rates_shock_10     0.0084      0.118      0.071      0.943      -0.224       0.241
oil prices_shock_10         0.1777      0.142      1.248      0.213      -0.103       0.459
inflation                   0.0029      0.010      0.300      0.764      -0.016       0.022
economy_shock_10            0.0578      0.144      0.402      0.688      -0.226       0.342
lag0                       -0.0422      0.072     -0.589      0.557      -0.183       0.099
lag1                       -0.0414      0.072     -0.579      0.564      -0.182       0.100
lag2                       -0.0897      0.071     -1.263      0.208      -0.230       0.050
==============================================================================
Omnibus:                        8.437   Durbin-Watson:                   1.976
Prob(Omnibus):                  0.015   Jarque-Bera (JB):                8.503
Skew:                          -0.501   Prob(JB):                       0.0142
Kurtosis:                       3.110   Cond. No.                         193.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 0.986921378475388
MAE: 0.7772298298266888

BTC-USD

In [220]:
# analyze performance for each metric and find best improvements
BTC_best_metrics = []
y_train = train['BTC-USD_shock_10_t+1']
y_test = test['BTC-USD_shock_10_t+1']
for kw in [i for i in BTC_kws if i!='memecoin']:
    for stat in ['','_diff','_shock_10']:

        y_train = pd.DataFrame()
        y_test = pd.DataFrame()
        y_train = train['BTC-USD_shock_10_t+1']
        y_test = test['BTC-USD_shock_10_t+1']
        X_train = pd.DataFrame()
        X_test = pd.DataFrame()
        X_train[kw+stat]=train[kw+stat]
        X_test[kw+stat]=test[kw+stat]
        X_train['lag0'] = train['BTC-USD_shock_10']
        X_test['lag0'] = test['BTC-USD_shock_10']
        X_train['lag1']=X_train['lag0'].shift(1)
        X_test['lag1']=X_test['lag0'].shift(1)
        X_train['lag2']=X_train['lag0'].shift(2)
        X_test['lag2']=X_test['lag0'].shift(2)
        X_train = X_train.dropna()
        X_test = X_test.dropna()
        y_train = y_train[X_train.index]
        y_test = y_test[X_test.index]
        X_train = sm.add_constant(X_train)
        X_test = sm.add_constant(X_test)

        model = sm.OLS(y_train,X_train).fit()
        predictions = model.predict(X_test)
        mse = mean_squared_error(y_test, predictions)
        if mse<BTC_base_mse:  # only analyze kw+stat pairs with improvement over baseline
            print(model.summary())
            print(f'MSE: {mse}')
            BTC_best_metrics.append((kw+stat,mse))

                             OLS Regression Results
================================================================================
Dep. Variable:     BTC-USD_shock_10_t+1   R-squared:                       0.011
Model:                              OLS   Adj. R-squared:                 -0.009
Method:                   Least Squares   F-statistic:                    0.5332
Date:                  Wed, 22 Apr 2026   Prob (F-statistic):              0.711
Time:                          22:28:48   Log-Likelihood:                -279.97
No. Observations:                   201   AIC:                             569.9
Df Residuals:                       196   BIC:                             586.5
Df Model:                             4
Covariance Type:              nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            -0.0663      0.181     -0.367      0.714      -0.422       0.290
bitcoin price     0.0045      0.006      0.778      0.438      -0.007       0.016
lag0              0.0094      0.072      0.130      0.896      -0.133       0.152
lag1             -0.0247      0.071     -0.347      0.729      -0.165       0.116
lag2              0.0866      0.072      1.210      0.228      -0.054       0.228
==============================================================================
Omnibus:                        0.661   Durbin-Watson:                   1.967
Prob(Omnibus):                  0.719   Jarque-Bera (JB):                0.791
Skew:                          -0.092   Prob(JB):                        0.673
Kurtosis:                       2.754   Cond. No.                         81.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 0.9492342329444324
                             OLS Regression Results
================================================================================
Dep. Variable:     BTC-USD_shock_10_t+1   R-squared:                       0.017
Model:                              OLS   Adj. R-squared:                 -0.003
Method:                   Least Squares   F-statistic:                    0.8286
Date:                  Wed, 22 Apr 2026   Prob (F-statistic):              0.508
Time:                          22:28:48   Log-Likelihood:                -279.37
No. Observations:                   201   AIC:                             568.7
Df Residuals:                       196   BIC:                             585.3
Df Model:                             4
Covariance Type:              nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                  0.0609      0.070      0.873      0.384      -0.077       0.198
bitcoin price_diff    -0.0111      0.008     -1.333      0.184      -0.027       0.005
lag0                   0.0138      0.072      0.193      0.847      -0.128       0.155
lag1                  -0.0384      0.072     -0.537      0.592      -0.180       0.103
lag2                   0.0821      0.071      1.152      0.251      -0.058       0.222
==============================================================================
Omnibus:                        1.115   Durbin-Watson:                   1.954
Prob(Omnibus):                  0.573   Jarque-Bera (JB):                1.223
Skew:                          -0.157   Prob(JB):                        0.543
Kurtosis:                       2.781   Cond. No.                         9.02
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 0.9436061485307188
                             OLS Regression Results
================================================================================
Dep. Variable:     BTC-USD_shock_10_t+1   R-squared:                       0.010
Model:                              OLS   Adj. R-squared:                 -0.010
Method:                   Least Squares   F-statistic:                    0.4825
Date:                  Wed, 22 Apr 2026   Prob (F-statistic):              0.749
Time:                          22:28:49   Log-Likelihood:                -280.07
No. Observations:                   201   AIC:                             570.1
Df Residuals:                       196   BIC:                             586.7
Df Model:                             4
Covariance Type:              nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
const                      0.0567      0.071      0.803      0.423      -0.083       0.196
bitcoin price_shock_10    -0.0426      0.067     -0.635      0.526      -0.175       0.090
lag0                       0.0108      0.072      0.149      0.882      -0.131       0.153
lag1                      -0.0318      0.072     -0.443      0.658      -0.173       0.110
lag2                       0.0795      0.072      1.108      0.269      -0.062       0.221
==============================================================================
Omnibus:                        0.558   Durbin-Watson:                   1.959
Prob(Omnibus):                  0.756   Jarque-Bera (JB):                0.693
Skew:                          -0.098   Prob(JB):                        0.707
Kurtosis:                       2.790   Cond. No.                         1.26
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 0.9502064784783096
                             OLS Regression Results
================================================================================
Dep. Variable:     BTC-USD_shock_10_t+1   R-squared:                       0.010
Model:                              OLS   Adj. R-squared:                 -0.010
Method:                   Least Squares   F-statistic:                    0.4982
Date:                  Wed, 22 Apr 2026   Prob (F-statistic):              0.737
Time:                          22:28:49   Log-Likelihood:                -280.04
No. Observations:                   201   AIC:                             570.1
Df Residuals:                       196   BIC:                             586.6
Df Model:                             4
Covariance Type:              nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.0435      0.076      0.575      0.566      -0.106       0.193
crypto crash     0.0054      0.008      0.683      0.496      -0.010       0.021
lag0             0.0073      0.073      0.101      0.919      -0.136       0.150
lag1            -0.0242      0.071     -0.339      0.735      -0.165       0.117
lag2             0.0865      0.072      1.208      0.228      -0.055       0.228
==============================================================================
Omnibus:                        0.538   Durbin-Watson:                   1.970
Prob(Omnibus):                  0.764   Jarque-Bera (JB):                0.677
Skew:                          -0.079   Prob(JB):                        0.713
Kurtosis:                       2.764   Cond. No.                         10.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 0.9499053873769571
                             OLS Regression Results
================================================================================
Dep. Variable:     BTC-USD_shock_10_t+1   R-squared:                       0.012
Model:                              OLS   Adj. R-squared:                 -0.008
Method:                   Least Squares   F-statistic:                    0.6104
Date:                  Wed, 22 Apr 2026   Prob (F-statistic):              0.656
Time:                          22:28:49   Log-Likelihood:                -279.81
No. Observations:                   201   AIC:                             569.6
Df Residuals:                       196   BIC:                             586.1
Df Model:                             4
Covariance Type:              nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.0634      0.070      0.907      0.365      -0.074       0.201
crypto crash_diff    -0.0069      0.007     -0.955      0.341      -0.021       0.007
lag0                  0.0189      0.072      0.262      0.794      -0.123       0.161
lag1                 -0.0381      0.072     -0.528      0.598      -0.181       0.104
lag2                  0.0831      0.071      1.164      0.246      -0.058       0.224
==============================================================================
Omnibus:                        1.068   Durbin-Watson:                   1.966
Prob(Omnibus):                  0.586   Jarque-Bera (JB):                1.168
Skew:                          -0.132   Prob(JB):                        0.558
Kurtosis:                       2.735   Cond. No.                         10.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 0.9477573289209121
                             OLS Regression Results
================================================================================
Dep. Variable:     BTC-USD_shock_10_t+1   R-squared:                       0.008
Model:                              OLS   Adj. R-squared:                 -0.013
Method:                   Least Squares   F-statistic:                    0.3823
Date:                  Wed, 22 Apr 2026   Prob (F-statistic):              0.821
Time:                          22:28:49   Log-Likelihood:                -280.28
No. Observations:                   201   AIC:                             570.6
Df Residuals:                       196   BIC:                             587.1
Df Model:                             4
Covariance Type:              nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                     0.0625      0.071      0.885      0.377      -0.077       0.202
crypto crash_shock_10     0.0051      0.067      0.076      0.939      -0.127       0.137
lag0                      0.0139      0.072      0.193      0.847      -0.128       0.156
lag1                     -0.0264      0.072     -0.369      0.713      -0.168       0.115
lag2                      0.0840      0.072      1.169      0.244      -0.058       0.226
==============================================================================
Omnibus:                        0.586   Durbin-Watson:                   1.961
Prob(Omnibus):                  0.746   Jarque-Bera (JB):                0.722
Skew:                          -0.091   Prob(JB):                        0.697
Kurtosis:                       2.770   Cond. No.                         1.23
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 0.9521348079832066
                             OLS Regression Results
================================================================================
Dep. Variable:     BTC-USD_shock_10_t+1   R-squared:                       0.016
Model:                              OLS   Adj. R-squared:                 -0.004
Method:                   Least Squares   F-statistic:                    0.8001
Date:                  Wed, 22 Apr 2026   Prob (F-statistic):              0.526
Time:                          22:28:49   Log-Likelihood:                -279.43
No. Observations:                   201   AIC:                             568.9
Df Residuals:                       196   BIC:                             585.4
Df Model:                             4
Covariance Type:              nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.2313      0.148      1.565      0.119      -0.060       0.523
crypto        -0.0062      0.005     -1.290      0.199      -0.016       0.003
lag0           0.0103      0.072      0.144      0.886      -0.131       0.152
lag1          -0.0352      0.071     -0.493      0.622      -0.176       0.106
lag2           0.0741      0.072      1.034      0.302      -0.067       0.215
==============================================================================
Omnibus:                        0.573   Durbin-Watson:                   1.954
Prob(Omnibus):                  0.751   Jarque-Bera (JB):                0.704
Skew:                          -0.104   Prob(JB):                        0.703
Kurtosis:                       2.798   Cond. No.                         65.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 0.9441460231081168
                             OLS Regression Results
================================================================================
Dep. Variable:     BTC-USD_shock_10_t+1   R-squared:                       0.019
Model:                              OLS   Adj. R-squared:                 -0.001
Method:                   Least Squares   F-statistic:                    0.9335
Date:                  Wed, 22 Apr 2026   Prob (F-statistic):              0.446
Time:                          22:28:49   Log-Likelihood:                -279.16
No. Observations:                   201   AIC:                             568.3
Df Residuals:                       196   BIC:                             584.8
Df Model:                             4
Covariance Type:              nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const           0.0631      0.070      0.905      0.366      -0.074       0.200
crypto_diff    -0.0164      0.011     -1.481      0.140      -0.038       0.005
lag0            0.0279      0.072      0.387      0.699      -0.115       0.170
lag1           -0.0422      0.072     -0.587      0.558      -0.184       0.099
lag2            0.0819      0.071      1.152      0.251      -0.058       0.222
==============================================================================
Omnibus:                        1.117   Durbin-Watson:                   1.988
Prob(Omnibus):                  0.572   Jarque-Bera (JB):                1.221
Skew:                          -0.143   Prob(JB):                        0.543
Kurtosis:                       2.747   Cond. No.                         6.84
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 0.9416252437375291
                             OLS Regression Results
================================================================================
Dep. Variable:     BTC-USD_shock_10_t+1   R-squared:                       0.033
Model:                              OLS   Adj. R-squared:                  0.013
Method:                   Least Squares   F-statistic:                     1.648
Date:                  Wed, 22 Apr 2026   Prob (F-statistic):              0.164
Time:                          22:28:49   Log-Likelihood:                -277.73
No. Observations:                   201   AIC:                             565.5
Df Residuals:                       196   BIC:                             582.0
Df Model:                             4
Covariance Type:              nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const               0.0562      0.069      0.811      0.418      -0.080       0.193
crypto_shock_10    -0.1316      0.059     -2.242      0.026      -0.247      -0.016
lag0                0.0006      0.071      0.008      0.994      -0.140       0.141
lag1               -0.0440      0.071     -0.621      0.536      -0.184       0.096
lag2                0.0724      0.071      1.023      0.307      -0.067       0.212
==============================================================================
Omnibus:                        1.891   Durbin-Watson:                   1.972
Prob(Omnibus):                  0.388   Jarque-Bera (JB):                1.810
Skew:                          -0.150   Prob(JB):                        0.404
Kurtosis:                       2.645   Cond. No.                         1.32
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 0.9283476939363855
                             OLS Regression Results
================================================================================
Dep. Variable:     BTC-USD_shock_10_t+1   R-squared:                       0.010
Model:                              OLS   Adj. R-squared:                 -0.010
Method:                   Least Squares   F-statistic:                    0.4876
Date:                  Wed, 22 Apr 2026   Prob (F-statistic):              0.745
Time:                          22:28:49   Log-Likelihood:                -280.06
No. Observations:                   201   AIC:                             570.1
Df Residuals:                       196   BIC:                             586.6
Df Model:                             4
Covariance Type:              nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const              0.1443      0.143      1.010      0.314      -0.137       0.426
cryptocurrency    -0.0031      0.005     -0.651      0.516      -0.012       0.006
lag0               0.0139      0.072      0.193      0.847      -0.128       0.156
lag1              -0.0290      0.071     -0.406      0.685      -0.170       0.112
lag2               0.0802      0.072      1.120      0.264      -0.061       0.221

In [250]:
# create model with 5 best metrics
BTC_t5 = sorted(BTC_best_metrics, key=lambda x: x[1])[:5]
for metric in BTC_t5:
    print(f'Metric: {metric[0]}   MSE: {metric[1]}')
BTC_t5 = [x[0] for x in BTC_t5]
y_train = train['BTC-USD_shock_10_t+1']
y_test = test['BTC-USD_shock_10_t+1']
X_train = pd.DataFrame()
X_test = pd.DataFrame()
X_train[BTC_t5]=train[BTC_t5]
X_test[BTC_t5]=test[BTC_t5]
X_train['lag0'] = train['BTC-USD_shock_10']
X_test['lag0'] = test['BTC-USD_shock_10']
X_train['lag1']=X_train['lag0'].shift(1)
X_test['lag1']=X_test['lag0'].shift(1)
X_train['lag2']=X_train['lag0'].shift(2)
X_test['lag2']=X_test['lag0'].shift(2)
X_train = X_train.dropna()
X_test = X_test.dropna()
y_train = y_train[X_train.index]
y_test = y_test[X_test.index]
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)

model = sm.OLS(y_train,X_train).fit()
predictions = model.predict(X_test)
mse = mean_squared_error(y_test, predictions)
print(model.summary())
print(f'MSE: {mse}')
print(f'MAE: {mean_absolute_error(y_test,predictions)}')

Metric: altcoin   MSE: 0.9217497651865896
Metric: altcoin_shock_10   MSE: 0.9255393357090946
Metric: crypto_shock_10   MSE: 0.9283476939363855
Metric: risk off_shock_10   MSE: 0.933010781729559
Metric: bitcoin mining_shock_10   MSE: 0.934969335685629
                             OLS Regression Results
================================================================================
Dep. Variable:     BTC-USD_shock_10_t+1   R-squared:                       0.069
Model:                              OLS   Adj. R-squared:                  0.030
Method:                   Least Squares   F-statistic:                     1.769
Date:                  Wed, 22 Apr 2026   Prob (F-statistic):             0.0853
Time:                          23:15:47   Log-Likelihood:                -273.91
No. Observations:                   201   AIC:                             565.8
Df Residuals:                       192   BIC:                             595.5
Df Model:                             8
Covariance Type:              nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       0.3019      0.174      1.732      0.085      -0.042       0.646
altcoin                    -0.0057      0.004     -1.595      0.112      -0.013       0.001
altcoin_shock_10           -0.0549      0.087     -0.634      0.527      -0.226       0.116
crypto_shock_10            -0.0325      0.095     -0.342      0.733      -0.220       0.155
risk off_shock_10           0.1370      0.077      1.785      0.076      -0.014       0.288
bitcoin mining_shock_10    -0.0253      0.077     -0.330      0.742      -0.177       0.126
lag0                       -0.0169      0.072     -0.235      0.814      -0.158       0.125
lag1                       -0.0469      0.071     -0.657      0.512      -0.187       0.094
lag2                        0.0381      0.072      0.531      0.596      -0.103       0.180
==============================================================================
Omnibus:                        1.252   Durbin-Watson:                   1.988
Prob(Omnibus):                  0.535   Jarque-Bera (JB):                1.339
Skew:                          -0.179   Prob(JB):                        0.512
Kurtosis:                       2.821   Cond. No.                         128.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 0.8936803403796855
MAE: 0.7676401107819594

TSLA

In [241]:
# analyze performance for each metric and find best improvements
TSLA_best_metrics = []
y_train = train['TSLA_shock_10_t+1']
y_test = test['TSLA_shock_10_t+1']
for kw in [i for i in TSLA_kws if i!='memecoin']:
    for stat in ['','_diff','_shock_10']:

        y_train = pd.DataFrame()
        y_test = pd.DataFrame()
        y_train = train['TSLA_shock_10_t+1']
        y_test = test['TSLA_shock_10_t+1']
        X_train = pd.DataFrame()
        X_test = pd.DataFrame()
        X_train[kw+stat]=train[kw+stat]
        X_test[kw+stat]=test[kw+stat]
        X_train['lag0'] = train['TSLA_shock_10']
        X_test['lag0'] = test['TSLA_shock_10']
        X_train['lag1']=X_train['lag0'].shift(1)
        X_test['lag1']=X_test['lag0'].shift(1)
        X_train['lag2']=X_train['lag0'].shift(2)
        X_test['lag2']=X_test['lag0'].shift(2)
        X_train = X_train.dropna()
        X_test = X_test.dropna()
        y_train = y_train[X_train.index]
        y_test = y_test[X_test.index]
        X_train = sm.add_constant(X_train)
        X_test = sm.add_constant(X_test)

        model = sm.OLS(y_train,X_train).fit()
        predictions = model.predict(X_test)
        mse = mean_squared_error(y_test, predictions)
        if mse<TSLA_base_mse:  # only analyze kw+stat pairs with improvement over baseline
            print(model.summary())
            print(f'MSE: {mse}')
            TSLA_best_metrics.append((kw+stat,mse))

                            OLS Regression Results
==============================================================================
Dep. Variable:      TSLA_shock_10_t+1   R-squared:                       0.041
Model:                            OLS   Adj. R-squared:                  0.022
Method:                 Least Squares   F-statistic:                     2.103
Date:                Wed, 22 Apr 2026   Prob (F-statistic):             0.0819
Time:                        22:51:42   Log-Likelihood:                -288.92
No. Observations:                 201   AIC:                             587.8
Df Residuals:                     196   BIC:                             604.4
Df Model:                           4
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const           0.3624      0.144      2.517      0.013       0.078       0.646
tesla stock    -0.0103      0.005     -2.262      0.025      -0.019      -0.001
lag0            0.0401      0.072      0.559      0.577      -0.102       0.182
lag1           -0.0247      0.071     -0.346      0.730      -0.166       0.116
lag2            0.0981      0.071      1.391      0.166      -0.041       0.237
==============================================================================
Omnibus:                        0.775   Durbin-Watson:                   1.998
Prob(Omnibus):                  0.679   Jarque-Bera (JB):                0.535
Skew:                           0.113   Prob(JB):                        0.765
Kurtosis:                       3.114   Cond. No.                         62.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.0376471513054057
                            OLS Regression Results
==============================================================================
Dep. Variable:      TSLA_shock_10_t+1   R-squared:                       0.017
Model:                            OLS   Adj. R-squared:                 -0.003
Method:                 Least Squares   F-statistic:                    0.8669
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.485
Time:                        22:51:42   Log-Likelihood:                -291.38
No. Observations:                 201   AIC:                             592.8
Df Residuals:                     196   BIC:                             609.3
Df Model:                           4
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0814      0.075      1.089      0.277      -0.066       0.229
tesla stock_diff    -0.0028      0.006     -0.501      0.617      -0.014       0.008
lag0                 0.0705      0.071      0.987      0.325      -0.070       0.211
lag1                 0.0009      0.072      0.013      0.990      -0.140       0.142
lag2                 0.1095      0.072      1.521      0.130      -0.032       0.251
==============================================================================
Omnibus:                        1.061   Durbin-Watson:                   1.993
Prob(Omnibus):                  0.588   Jarque-Bera (JB):                0.934
Skew:                           0.167   Prob(JB):                        0.627
Kurtosis:                       3.012   Cond. No.                         14.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.063371157216454
                            OLS Regression Results
==============================================================================
Dep. Variable:      TSLA_shock_10_t+1   R-squared:                       0.021
Model:                            OLS   Adj. R-squared:                  0.001
Method:                 Least Squares   F-statistic:                     1.030
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.393
Time:                        22:51:42   Log-Likelihood:                -291.05
No. Observations:                 201   AIC:                             592.1
Df Residuals:                     196   BIC:                             608.6
Df Model:                           4
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                    0.0793      0.075      1.062      0.290      -0.068       0.227
tesla stock_shock_10    -0.0787      0.083     -0.945      0.346      -0.243       0.086
lag0                     0.0676      0.071      0.948      0.344      -0.073       0.208
lag1                    -0.0038      0.071     -0.054      0.957      -0.145       0.137
lag2                     0.1104      0.071      1.544      0.124      -0.031       0.251
==============================================================================
Omnibus:                        0.847   Durbin-Watson:                   1.996
Prob(Omnibus):                  0.655   Jarque-Bera (JB):                0.734
Skew:                           0.148   Prob(JB):                        0.693
Kurtosis:                       3.008   Cond. No.                         1.33
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.059903213649609
                            OLS Regression Results
==============================================================================
Dep. Variable:      TSLA_shock_10_t+1   R-squared:                       0.020
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                    0.9956
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.411
Time:                        22:51:42   Log-Likelihood:                -291.12
No. Observations:                 201   AIC:                             592.2
Df Residuals:                     196   BIC:                             608.8
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.1620      0.118      1.376      0.171      -0.070       0.394
elon musk     -0.0080      0.009     -0.870      0.385      -0.026       0.010
lag0           0.0609      0.072      0.842      0.401      -0.082       0.204
lag1          -0.0090      0.072     -0.125      0.900      -0.151       0.133
lag2           0.1001      0.071      1.402      0.163      -0.041       0.241
==============================================================================
Omnibus:                        1.151   Durbin-Watson:                   1.986
Prob(Omnibus):                  0.562   Jarque-Bera (JB):                1.005
Skew:                           0.173   Prob(JB):                        0.605
Kurtosis:                       3.022   Cond. No.                         20.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.0606332129302585
                            OLS Regression Results
==============================================================================
Dep. Variable:      TSLA_shock_10_t+1   R-squared:                       0.020
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                    0.9860
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.416
Time:                        22:51:42   Log-Likelihood:                -291.14
No. Observations:                 201   AIC:                             592.3
Df Residuals:                     196   BIC:                             608.8
Df Model:                           4
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const              0.0821      0.075      1.100      0.273      -0.065       0.229
elon musk_diff    -0.0091      0.011     -0.848      0.397      -0.030       0.012
lag0               0.0646      0.072      0.901      0.369      -0.077       0.206
lag1               0.0020      0.071      0.028      0.978      -0.139       0.143
lag2               0.1089      0.071      1.525      0.129      -0.032       0.250
==============================================================================
Omnibus:                        1.073   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.585   Jarque-Bera (JB):                0.934
Skew:                           0.167   Prob(JB):                        0.627
Kurtosis:                       3.020   Cond. No.                         7.32
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.0608378154558926
                            OLS Regression Results
==============================================================================
Dep. Variable:      TSLA_shock_10_t+1   R-squared:                       0.029
Model:                            OLS   Adj. R-squared:                  0.009
Method:                 Least Squares   F-statistic:                     1.466
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.214
Time:                        22:51:42   Log-Likelihood:                -290.18
No. Observations:                 201   AIC:                             590.4
Df Residuals:                     196   BIC:                             606.9
Df Model:                           4
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                  0.0714      0.075      0.956      0.340      -0.076       0.219
elon musk_shock_10    -0.1117      0.069     -1.615      0.108      -0.248       0.025
lag0                   0.0573      0.071      0.802      0.424      -0.084       0.198
lag1                  -0.0065      0.071     -0.092      0.927      -0.147       0.134
lag2                   0.1042      0.071      1.469      0.143      -0.036       0.244
==============================================================================
Omnibus:                        0.880   Durbin-Watson:                   1.977
Prob(Omnibus):                  0.644   Jarque-Bera (JB):                0.723
Skew:                           0.146   Prob(JB):                        0.697
Kurtosis:                       3.040   Cond. No.                         1.28
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.0507552896011207
                            OLS Regression Results
==============================================================================
Dep. Variable:      TSLA_shock_10_t+1   R-squared:                       0.031
Model:                            OLS   Adj. R-squared:                  0.012
Method:                 Least Squares   F-statistic:                     1.589
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.179
Time:                        22:51:42   Log-Likelihood:                -289.94
No. Observations:                 201   AIC:                             589.9
Df Residuals:                     196   BIC:                             606.4
Df Model:                           4
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.7517      0.388      1.939      0.054      -0.013       1.516
self driving car    -0.0112      0.006     -1.758      0.080      -0.024       0.001
lag0                 0.0486      0.072      0.675      0.501      -0.093       0.191
lag1                -0.0078      0.071     -0.110      0.913      -0.148       0.132
lag2                 0.1145      0.071      1.611      0.109      -0.026       0.255
==============================================================================
Omnibus:                        1.180   Durbin-Watson:                   1.977
Prob(Omnibus):                  0.554   Jarque-Bera (JB):                0.943
Skew:                           0.161   Prob(JB):                        0.624
Kurtosis:                       3.092   Cond. No.                         321.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.0481984364082513
                            OLS Regression Results
==============================================================================
Dep. Variable:      TSLA_shock_10_t+1   R-squared:                       0.028
Model:                            OLS   Adj. R-squared:                  0.008
Method:                 Least Squares   F-statistic:                     1.412
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.231
Time:                        22:51:42   Log-Likelihood:                -290.29
No. Observations:                 201   AIC:                             590.6
Df Residuals:                     196   BIC:                             607.1
Df Model:                           4
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                     0.0794      0.074      1.067      0.287      -0.067       0.226
self driving car_diff    -0.0096      0.006     -1.548      0.123      -0.022       0.003
lag0                      0.0660      0.071      0.929      0.354      -0.074       0.206
lag1                      0.0124      0.072      0.173      0.863      -0.129       0.154
lag2                      0.1194      0.072      1.668      0.097      -0.022       0.261
==============================================================================
Omnibus:                        0.695   Durbin-Watson:                   1.998
Prob(Omnibus):                  0.706   Jarque-Bera (JB):                0.725
Skew:                           0.140   Prob(JB):                        0.696
Kurtosis:                       2.907   Cond. No.                         12.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.0518785842212572
                            OLS Regression Results
==============================================================================
Dep. Variable:      TSLA_shock_10_t+1   R-squared:                       0.020
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     1.023
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.396
Time:                        22:51:42   Log-Likelihood:                -291.07
No. Observations:                 201   AIC:                             592.1
Df Residuals:                     196   BIC:                             608.7
Df Model:                           4
Covariance Type:            nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                         0.0767      0.075      1.024      0.307      -0.071       0.224
self driving car_shock_10    -0.0733      0.079     -0.931      0.353      -0.229       0.082
lag0                          0.0626      0.072      0.871      0.385      -0.079       0.204
lag1                         -0.0006      0.071     -0.009      0.993      -0.141       0.140
lag2                          0.1147      0.072      1.593      0.113      -0.027       0.257
==============================================================================
Omnibus:                        1.111   Durbin-Watson:                   1.985
Prob(Omnibus):                  0.574   Jarque-Bera (JB):                1.005
Skew:                           0.173   Prob(JB):                        0.605
Kurtosis:                       2.994   Cond. No.                         1.33
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 1.0600466621130498
                            OLS Regression Results
==============================================================================
Dep. Variable:      TSLA_shock_10_t+1   R-squared:                       0.019
Model:                            OLS   Adj. R-squared:                 -0.001
Method:                 Least Squares   F-statistic:                    0.9484
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.437
Time:                        22:51:42   Log-Likelihood:                -291.22
No. Observations:                 201   AIC:                             592.4
Df Residuals:                     196   BIC:                             609.0
Df Model:                           4
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.5271      0.593      0.889      0.375      -0.642       1.696
electric vehicles    -0.0070      0.009     -0.756      0.451      -0.025       0.011
lag0                  0.0644      0.072      0.896      0.371      -0.077       0.206
lag1                 -0.0060      0.072     -0.084      0.933      -0.148       0.136
lag2                  0.1018      0.071      1.427      0.155      -0.039       0.243
==============================================================================
Omnibus:                        1.346   Durbin-Watson:                   1.990

In [251]:
# create model with 5 best metrics
TSLA_t5 = sorted(TSLA_best_metrics, key=lambda x: x[1])[:5]
for metric in TSLA_t5:
    print(f'Metric: {metric[0]}   MSE: {metric[1]}')
TSLA_t5 = [x[0] for x in TSLA_t5]
y_train = train['TSLA_shock_10_t+1']
y_test = test['TSLA_shock_10_t+1']
X_train = pd.DataFrame()
X_test = pd.DataFrame()
X_train[TSLA_t5]=train[TSLA_t5]
X_test[TSLA_t5]=test[TSLA_t5]
X_train['lag0'] = train['TSLA_shock_10']
X_test['lag0'] = test['TSLA_shock_10']
X_train['lag1']=X_train['lag0'].shift(1)
X_test['lag1']=X_test['lag0'].shift(1)
X_train['lag2']=X_train['lag0'].shift(2)
X_test['lag2']=X_test['lag0'].shift(2)
X_train = X_train.dropna()
X_test = X_test.dropna()
y_train = y_train[X_train.index]
y_test = y_test[X_test.index]
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)

model = sm.OLS(y_train,X_train).fit()
predictions = model.predict(X_test)
mse = mean_squared_error(y_test, predictions)
print(model.summary())
print(f'MSE: {mse}')
print(f'MAE: {mean_absolute_error(y_test,predictions)}')

Metric: battery technology   MSE: 1.0281727441497939
Metric: tesla stock   MSE: 1.0376471513054057
Metric: battery technology_shock_10   MSE: 1.0456790652111292
Metric: tesla crash_shock_10   MSE: 1.0475095863038517
Metric: self driving car   MSE: 1.0481984364082513
                            OLS Regression Results
==============================================================================
Dep. Variable:      TSLA_shock_10_t+1   R-squared:                       0.080
Model:                            OLS   Adj. R-squared:                  0.041
Method:                 Least Squares   F-statistic:                     2.080
Date:                Wed, 22 Apr 2026   Prob (F-statistic):             0.0395
Time:                        23:16:00   Log-Likelihood:                -284.79
No. Observations:                 201   AIC:                             587.6
Df Residuals:                     192   BIC:                             617.3
Df Model:                           8
Covariance Type:            nonrobust
===============================================================================================
                                  coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
const                           1.3672      0.632      2.163      0.032       0.120       2.614
battery technology             -0.0111      0.012     -0.912      0.363      -0.035       0.013
tesla stock                    -0.0051      0.005     -1.012      0.313      -0.015       0.005
battery technology_shock_10    -0.0406      0.125     -0.325      0.746      -0.287       0.206
tesla crash_shock_10           -0.1017      0.075     -1.356      0.177      -0.249       0.046
self driving car               -0.0102      0.006     -1.583      0.115      -0.023       0.003
lag0                            0.0167      0.072      0.231      0.818      -0.126       0.159
lag1                           -0.0204      0.071     -0.288      0.774      -0.160       0.119
lag2                            0.1199      0.071      1.692      0.092      -0.020       0.260
==============================================================================
Omnibus:                        0.180   Durbin-Watson:                   1.966
Prob(Omnibus):                  0.914   Jarque-Bera (JB):                0.092
Skew:                           0.052   Prob(JB):                        0.955
Kurtosis:                       3.017   Cond. No.                         731.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
MSE: 0.9958577604846891
MAE: 0.7817667820869008